### ISSUE TITLE
This would be fantastic for demo purposes if the distance could be displayed alongside the grid locator

### ISSUE THREAD

**Issue by gvdw** [PA7T/sdr_wspr#7]
Showing distance as well would be epic

**Comment by PA7T** [comment]
Dear Geoff,

Where would you like to see it? The analysis part is mainly meant to take place at wsprlive.net
So in case you would like to have an account, just let me know, and you can get your distance information from there.

73 de PA7T / DL2ZZ

**Comment by gvdw** [comment]
I had in mind to use a Red Pitaya and a laptop as a demo for ham radio to non-hams.  Since it's a portable and temporary setup it is greatly simplified by having something self-contained ie RP and laptop can plug in via network cable without requiring any internet access.

**Comment by PA7T** [comment]
Dear Geoff,

I see. the issue is that the display on the website is simply showing the raw output from the wspr decode. the calculations for the distance are done in the wsprlive uploader scripts. thats why this is not so easily implementable. 

73 de PA7T / DL2ZZ

**Comment by gvdw** [comment]
OK, no problem.  Thanks for your time :)
